### ISSUE TITLE
Diverse stavfel / various spelling errors

### ISSUE THREAD

**Issue by annettekusma** [dbwebb-se/python#28]
Hittade några stavfel i README-filen i python-repot och när man uppmanas att bidra och öppna ärenden så kan jag ju inte låta bli att testa. Here goes:

"swedish target" ska vara stort s i landsadjektivet
"as the first course" kanske borde heta "their first course"? Är kanske inte första programmeringskursen i Sverige? 
"on university level" låter bättre och ger fler sökträffar med "at university level"
"and has the need" bör stå "have" eftersom det tidigare stått "those who are"
"python" med stort P
"aqauinted" -> "acquainted" OBS två fel: c och ua
"Dive intro Python" -> "into"

Hoppas ingen känner sig trampad på tån, men det verkar ju vara tänkt att texten läses av hela världen och några länder därute är petigare med stavning än vi är. Och så måste jag ju prova att öppna en issue.

**Comment by mosbth** [comment]
Lagade i commit här:
https://github.com/dbwebb-se/python/commit/7fa769aa0263e5e9975104b76a0243405b2b8cc1
