### ISSUE TITLE
Åtgärder inför HT18

### ISSUE THREAD

**Issue by emilfolino** [dbwebb-se/python#31]
* Lab1 uppgift 3.1 ska ersättas med en som går att lösa med programmering.

* Formulera om Lab2 4.2 så den är lättare att förstå.

**Comment by mosbth** [comment]
### Kursutvärdering

Kursen gick för programmet ITsäk. Länk till utvärderingen: http://bfm.bth.se/public/rapport/d4ece725-1a59-4bf9-b5fa-6016383f4f68

Utskick till 18 varav 5 svarade. Snitt 3.5.

**Comment by emilfolino** [comment]
Utifrån fritext kommentarer och löpande feedback under kursen konstateras att studenter överlag är nöjda med upplägget distanskurs på campus. Trots studenternas tidigare kunskapar i programmering gav inlämningsuppgifter i slutet av kursen och den individuella examinationen utmaningar. Den individuella examinationen växer på ett bra sätt med studenternas kunskap.

Vi tar till förbättringsförslagen med bättre introduktion av argparse, json. Kritiken av att ASCII-bilderna i projektet är fullt förståelig och att det stjäl tid från programmering och mjukvarudesignen är något vi får utvärdera inför kommande kurstillfällen. Vi ser till att alla filer validerar inför nästa kursomgång. Vi funderar över val av språk i uppgiftsbeskrivningar och övningar ytterligare en gång, utvärderar inför nästa kurstillfälle.

En generell översyn av material (video, kurslitteratur, övningar och artiklar) är planerad inför HT18.

**Comment by mosbth** [comment]
Funderingar inför framtida utvecklingar av kursen.

* Rekursion (ut eller in)
* Generatorer (ut eller in)
* Överväg hur mycket trycka på pythonic code? Viss inspiration här: https://www.youtube.com/watch?v=o0LohkA3UR4
* Lyft fram hantering av exception (används redan i kmom01/02)
* Hur jobba med cli options och arguments? Kanske enklare och bara använda argv/argc.

**Comment by AndreasArne** [comment]
- Allmänt
    - Visa exempel på hur saker används i artiklar, inte bara presentera hur det funkar. ge det context.
    - Automat rätta marvin.
    - Kolla över redovisningsfrågor
    - Fler videos - kan se ut när klart
- kmom01
    - plane uppgift
         * Så här kan de se ut när du är klar video
    - lab1
        * Näst sista uppgift fixa 
- kmom02
    - marvin
       * fixa numrering av menyvalen+ extra uppgifter
- kmom03
    - flytta moduler till kmom04.
   - funktioner artikel
        * utöka
    - marvin steg 2
        * Ta uppgifter från steg 1 - för gör av med moduler
- kmom04
    - Ny artikel med mer avancerade funktioner
    - lägg modul artikel här, utöka den.
    - flytta listor till mom05
- kmom05
    - dicts till kmom06
- kmom06    
    - kommando loop istället för argparse för analys upgift.
    - ta bort argparse
- tenta
    - genrell ROT uppgift
    - extra uppift stuk på uppgifter
    - ta uppgift från tidigare kmoms och förändra lite

**Comment by AndreasArne** [comment]
Kan göra tenta med labverktyget typ.
Studntens filer och funktioner måste ha rätt namn för få godkänt och kunna köra tester.
I dbwebb.py finns enhetstester som testar varje uppgift.
Kör checksum på dbwebb.py för kolla så den inte har blivit redigerad.
Kommandon:
create exam -- hämta och skapa filer, med tidsstämpel för distansare
correct exam -- kör tester för visa betyg och validera
publish exam -- ladda upp på studservern och validera, kolla checksum.

**Comment by emilfolino** [comment]
Gör eget betygsättningsdokument för python: kurser/python-v2#betyg
