### ISSUE TITLE
Anpassa Marvin för automaträttning/inspect

### ISSUE THREAD

**Issue by emilfolino** [dbwebb-se/python#32]
Använd siffror i kmom02 1, 2, 3, 4, 5
Sedan kör bokstäver i kmom03 A, B, C, D

Så vi alltid har samma när vi ska rätta även om studenter har gjort extra uppgifter. Anpassa så inspect kan köra kommandon inne i marvin.

**Comment by AndreasArne** [comment]
Done, med dbwebb test kommandot
