### ISSUE TITLE
Tänk på till HT19

### ISSUE THREAD

**Issue by AndreasArne** [dbwebb-se/python#33]
<strike>* kmom02
    * Många frågor om marvin1 menyval 4. De förstår inte tänket, visa upp på genomgång/föreläsning liknande exempel.
    * Studenter har svårt för menyval 7. Samma som ovan.
    * På föreläsning gå igenom en exekvering av nestlad forloop på tavlan, visa hur värden ändras i loop. Isogram uppgiften är ett bra exempel med 2 for-loopar för räkna antalet gågner en bokstav finns i ett ord.
</strike>
Spelade in video.

**Comment by emilfolino** [comment]
Kanske mitigera problemet redan i år genom att spela in video? Imorgon?

**Comment by AndreasArne** [comment]
Ta bort extra uppgift två i marvin 2? brackets, väldigt avancerad utan listor och dicts.

**Comment by emilfolino** [comment]
Kanske flytta någon eller några menyval från vanliga till extrauppgifter.

**Comment by emilfolino** [comment]
I genomgången till kmom03 utgå från ett färdigt exempel på marvin1 och bryt ut till funktioner och visa hur funktionerna ska läggas högst upp och enbart ha kvar funktionsanropen i if-elif delen.

**Comment by AndreasArne** [comment]
menyval 3 och 11, specifiera hur de ska lösa eller ändra.

**Comment by AndreasArne** [comment]
Lägg till p4e stärng chapter i kmom03, mycket sträng manipulering i det kmom?

**Comment by AndreasArne** [comment]
Foruminlägg eller artikeln om att radbryta olika typer av too long lines

**Comment by emilfolino** [comment]
Lägg till om isinstance kanske redan i kmom01.

**Comment by emilfolino** [comment]
Vid det här laget är jag ganska trött på att saker som inte finns med i kurslitteraturen blandas in i uppgifterna. Jag hade önskat en kurslitteratur där allt fanns samlat. Det blir så rörigt när informationen är utspridd i litteratur, videor, artiklar, kursforum m.m. Jag tycker också att det är lite konstigt hur man går igenom väldigt enkla moment noggrant, men sedan blandar in nya saker utan någon förklaring eller med väldigt sparsam sådan.

**Comment by emilfolino** [comment]
Specificera att avrundning ska ligga utanför funktionerna av fysik uppgifterna.

**Comment by emilfolino** [comment]
Jodå. Något jag tycker saknas i lektionstexten är att beskriva hur __name__ kan användas, och att berätta att när man gör en import så exekveras all kod på toppnivå i filen. Det för att man tex kan för-ladda eller pre-processa saker när allt importeras. 

Något annat jag saknat är hur python hanterar globala variabler mellan funktioner och olika moduler.

**Comment by AndreasArne** [comment]
"många" missar att göra menyval 12, krav 3. https://dbwebb.se/uppgift/din-egen-chattbot-marvin-steg-3-v2#krav. De verkar tro att det är en del av citat. Kan man byta ordning eller skriva om så det blir mer tydligt?

**Comment by AndreasArne** [comment]
Exam:
- Många förstår inte/missar att de behöver ändra docstring.
- Många har för många inputs/outputs.
- Ha inte asserts if true/false. 
    - Ha alltid så de kan se värdet som skickas in så de kan jämföra. Har behövt länka exempel värden många gånger. Specielt lista när outut är True/False.

**Comment by AndreasArne** [comment]
- Flera har skrivit att de hade velat se facit på kursmomenten.
- "På dbwebb fanns ingen läsanvisning till kapitel 6 trots att vi jobbade mycket med strängmanipulering. Det bör åtgärdas till nästa år. "
- "Både Andreas och Emil förklarade koncepten tydligt och pedagogiskt, även om de ibland använde sig av för mig okända tekniska termer (typ "parsa") lite slentrianmässigt."
    - Andra har också skrivit typ detta.

**Comment by emilfolino** [comment]
Exemplifiera alla examinationsuppgifter

**Comment by emilfolino** [comment]
Exemplifiera vad python kan användas för i webb sammanhang koppla mot oopython.

**Comment by AndreasArne** [comment]
jag hade önskat ändå om i kursens allra början kunna ta lite tid berätta lite om hur man söker lösning och svar via internet inom programmering, samt hur man söka och tolka i Python Document (det som Emil gjorde när han gick igenom metoder för listor var väldigt bra), för jag bekantade mig med det efter ett tag,

**Comment by emilfolino** [comment]
Kanske ha en lite längre inspirationsföreläsning under introveckan liknande denna: https://youtu.be/z-OxzIC6pic

Komplettera med TEDed videos som förklarer på ett kort och koncist sätt hur olika saker fungerar: https://ed.ted.com/lessons/your-brain-can-solve-algorithms-david-j-malan

Kanske även nått för oopython och algoritm delar där?

**Comment by AndreasArne** [comment]
Introdusera listor i kmom02? för for each förklarande... för att lösa problem i kmom04.

**Comment by emilfolino** [comment]
Skapa extralabbar som är firvilliga med många lätta uppgifter som sätter koncepten.

**Comment by emilfolino** [comment]
Använda visualisering av flöden till ex.: http://www.pythontutor.com/visualize.html

**Comment by emilfolino** [comment]
Fixa labbar så de inte innehåller faktafel. Laddning av bilar och fysik uppgifter. 

Ta bort krav om att använda  marvin3 i marvin11, men försöka få till återanvänding av funktioner, kan bli svårt.

**Comment by emilfolino** [comment]
Video till kmom01 för att introducera programmering: https://www.youtube.com/watch?v=qDbsiVWA2Ag

**Comment by AndreasArne** [comment]
Massa extrauppgifter för kmom02, nu när det är en veckan längre.

**Comment by AndreasArne** [comment]
Asciinema kmom01, https://dbwebb.se/kunskap/introduktion-till-variabler-och-datatyper

**Comment by AndreasArne** [comment]
Ny redovisningsvideo  https://dbwebb.se/kurser/python/redovisa#klar

**Comment by AndreasArne** [comment]
Lägg till om readlines() i https://dbwebb.se/kunskap/att-lasa-filer-i-python

**Comment by AndreasArne** [comment]
Spela in ny ascineema för text analys solution https://dbwebb.se/uppgift/analysera-text-och-ord-v2

**Comment by AndreasArne** [comment]
Foruminlägg eller artikeln om att radbryta olika typer av too long lines

**Comment by AndreasArne** [comment]
Lägg till ett facit på analyzer, vad är rätt svar på antalet och procenten osv.

**Comment by AndreasArne** [comment]
Valider example mappen
