### ISSUE TITLE
HT20

### ISSUE THREAD

**Issue by emilfolino** [dbwebb-se/python#36]
Återkoppling HT19

**Comment by AndreasArne** [comment]
I t.ex. kmom03 ska de använda random modulen i marvin men vi går inte igenom den i någon övning eller så tidigare. Hur ska de veta om den?

Gör om kommandona för plane uppgiften i kmom01. Nu får de problem som inte gjort övningen.

**Comment by AndreasArne** [comment]
Vi måste ha bättre koppling till uppgifterna i materialet. 
Föreläsningar/genomgågar/artiklar går grundligt igenom koncepten men de tar inte upp funktioner och lösningar som studenterna ska använda i uppgifterna. 
Studenterna vet inte hur de ska lösa uppgifterna för att de vet inte att vissa funktioner finns. Ex. random och för inventory vet de inte hur de kan plocka ut ett item ur inv pick/drop osv.

**Comment by AndreasArne** [comment]
Styra upp krav 2 i marvin citat? https://dbwebb.se/uppgift/din-egen-chattbot-marvin-citat#krav
Lite förvirrande uppgift men länk till den stora github filen.

**Comment by AndreasArne** [comment]
Kmom06:
Typ inga lyckas lösa att byta filnamn. Många kör med global variabel men vi har inte visat dem hur man kan ändra på globala variabler. Sen är det många som bara inte har någon aning.

Många saknar en main() funktion. De kommer inte ihåg/förstår "if __name__ == "__main__"". Många har en input i slutet av sin while-loop.

**Comment by AndreasArne** [comment]
FIXA inspect så det skriver ut filernas innehåll!!!!!

**Comment by AndreasArne** [comment]
För bättre felutskriften i exam kan vi lägga try catch runt testerna och ge tips beroende på felet.

**Comment by AndreasArne** [comment]
Uppdater exam prep så testerna är mer som i nya och skriv exempel för uppgifterna.

**Comment by AndreasArne** [comment]
Fel i lab5 enligt en stud.
Exercise 3.2 extra assignments, Lab 5

The list :

[123, 4, 125, 69, 155]

uppgiften säger att vi skulle multiplicera:

The function should multiply all even numbers by 3 and add 5 to all odd numbers.

men hinten visar annan sak:

Hint:

[160, 130, 128, 74, 12]
så man kan inte multiplesera utan man skulle addera istället,

och när jag har adderad istället fick jag fel på sista element :D

[160, 130, 128, 74, 7]

Jag har fixat det själv med att multiplicera sista element med 3.

**Comment by AndreasArne** [comment]
Gör om kmom05 uppgifter? Borde finnas bättre uppgifter att använda listor på.

**Comment by AndreasArne** [comment]
Kommentarer på tentan:
uppgift 1:
    - ska vara case-sensitive
    - ska bara ersätta hela ord, inte input som är del av ett annat ord
    - vissa av tester svår tydliga. Kolla om vi kan lägga till en print vid varje assert som förklar vad det är som har testats.
    - man får inte använda moduler (ex regex)
    - Vissa får valideringsfel att deras output.txt fil har clrf radslut.
    - För svår antar jag iom att typ inga klarar den.
    - Skulle lagt den sist så att inte alla hade fastnat på den utan att gå vidare.
    - Var tydligare med att bara gå vidare.

**Comment by AuroraBTH** [comment]
Extrauppgift på `analyzer` uppgiften eftertraktas

**Comment by AndreasArne** [comment]
Kmom06:
Vissa får inte med .dbwebb för kmom06. Tar inte kommandot med . mappar för något os? Kanske mac eller linux?

**Comment by AndreasArne** [comment]
Inspect:
visa filers innehåll.

**Comment by AndreasArne** [comment]
Frankling: lägg till rättar texter för kmoms:
    kmom05: 
    kmom06: Jag har kollat att du har delat upp koden i moduler och att du analyserar texten korrekt i menyvalen. Bra förklaring av tupler och dictionaries.

**Comment by AndreasArne** [comment]
Uppdateran text_dbwebb.py:
Ger fel på testerna ett exception man kan fånga? Då kan vi skriva ut vad testet kollar efter, input och förväntad output och vad de ger för output.
Kanske att upgiftern är utkommenterade i exam.py och att de behöver kommentera av dem och först då syns output för de uppgifterna i rättningen.

**Comment by AndreasArne** [comment]
Förklarr dååligt vad if__name__ == "__main__" är. Typ ingen som vet vad det är, bara att vi har nämnt det.
VI behöver utveckla övningarna så de innehåller men än bara den specifika konstruktionen. Visa även saker de behöver för att lösauppgifterna.

**Comment by AndreasArne** [comment]
Kolla kursplanen så det inte står att vi ska använda python för webben. För vi gör inget sånt längre?

**Comment by AndreasArne** [comment]
Krav om ansikte och körkort i distansvideos?

**Comment by AndreasArne** [comment]
I början av kursen gå igenom varför vi har vårt upplägg och varför vi inte kör grupparbete, validering istället för feedback och allt sånt som vi sen skriver i kursvärderingsfeedback.Gör detta ibörjan av kursen och senare.

**Comment by AndreasArne** [comment]
Gå igenom kursvärderingsfeedback https://docs.google.com/document/d/1ZWKgXFUdg24YoUJmLbyvBEB4bXdH6YPjncm8kZPKzlM/edit

**Comment by AndreasArne** [comment]
Registera examination centralt så att de inte krockar med SE matte tentorna hela tide....

**Comment by emilfolino** [comment]
Skapa kataloger för 10/10 programmen och eventuella filer att utgå ifrån i exempel katalogen, som enkelt kopieras till me katalogen.

**Comment by AndreasArne** [comment]
Att tänka på till uppgifter och tenan. På omtentan gjorde alla väldigt mycket mer avancerade och komplicerade lösningar som behövs. På så sätt gjorde de uppgifterna mycket svårare för sig själva. Kan vi förhindra dätta på något sätt.

**Comment by AndreasArne** [comment]
Någonstans visa/gå igenom hur/vad python används till på riktigt.

**Comment by AndreasArne** [comment]
Hur hantera soretade dictionaries? 3.7 så är de sorterade by default men inte i tidigare versioner.
Kanske inget problem om det har uppdaterat studentservern tills då.

**Comment by AndreasArne** [comment]
Ändra till inlämning varannan vecka,så blir mindre att rätta och ge mer strukturell kompleteringar.

**Comment by AndreasArne** [comment]
https://www.freecodecamp.org/news/how-to-think-like-a-programmer-lessons-in-problem-solving-d1d8bf1de7d2/

**Comment by AndreasArne** [comment]
Kör med https://thonny.org/ pyhton editor kmom01-03? För debugging
