### ISSUE TITLE
Marvin1 kmom02

### ISSUE THREAD

**Issue by daviidandersson** [dbwebb-se/python#41]
Hej!

Jag har haft problem med menyval 6 i marvin för kmom02. Min elif choice == "6": funkar inte och vet inte varför den inte funkar.
Har frågat i discord men vi lyckades inte få det att fungera.
så här ser min code ut:  https://codeshare.io/5P7XNE

Tack på för hand!

**Comment by AndreasArne** [comment]
Hej david
Om du har thonny installerat, kopiera in koden där och kör debuggern. Skriv in 6 som menyval och följ med hur python exekverar koden. Då borde du se var din if-sats avbryts och gör att din elif inte hänger med.
PS när du fråga efter hjälp, skriv vad det är som inte funkar och vad du får för fel. Att bara skriva att menyval 6 inte funkar säger inte oss mycket om vad du behöver hjälp med. Det kan också hjälpa dig att komma på svaret själv om du måste beskriva vad det är som inte funkar.
