### ISSUE TITLE
feedback från studenter HT21

### ISSUE THREAD

**Issue by AndreasArne** [dbwebb-se/python#50]

**Comment by jeso20BTH** [comment]
Något jag fastnade på när jag skulle komma igång med kursen var först och främst att hitta in till kurssidan på Canvas. Det mail jag fick angående att det var Canvas som gällde kom till skolmailen, vilken jag inte ens var medveten om att jag hade en. Därför blev det, när jag väl hittade in, väldigt mycket information att ta in på en gång. Det var otroligt många sidor text som skulle läsas igenom för att komma igång med allt. Informationen som fanns där känner jag inte att det var något fel på, men det var förvirrande med så många olika instruktionssidor på dbwebb.se som man var tvungen att hoppa mellan. Det tog helt enkelt ett tag att sätta sig in i hur kursen var uppbyggd.

Vid valideringsfel tycker jag det är lite svårt att hitta felet, det känns som att det är lite gömt bland den övriga texten. Hade underlättat om det stod längst ner i resultatrapporten för att enkelt hitta informationen om vad som blev fel.

**Comment by jeso20BTH** [comment]
Det gick bra att använda dbwebb test. Ingen feedback på det, dock tycker jag att fråga 3.1 på lab1 var felformulerad: "On a windy and sunny day in September the sun shines for 10 hours with an average output effect of the solar panels of 9345 W per hour for all 24 hours of the day." Jag skulle ha tagit bort biten om "24 hours of the day," för svaret verkade bero på att genomsnittet var faktiskt för 10 timmar. Det var förvirrande för mig och jag kunde inte räkna ut varför det ens stod det där om 10 timmar om vi sedan fick effekten under ett dygn.

**Comment by jeso20BTH** [comment]
Är du bekant med terminalen och Unix-kommandon sedan tidigare?
Jag har provat installera grejer via terminalen i de andra kurserna men ärligt talat är det den svåraste biten för mig. Tycker det är väldigt abstrakt och skulle gärna haft en lite mer övergripande genomgång på det området.

Gick det bra att komma i gång med kursmomentet, fanns det svårigheter som du fastnade på?
Att komma igång gick bra men jag tycker det är lite rörigt. En sida med kort men övergripande info på alla övningar i ett moment och vilka filer det borde ha genererat när man är klar skulle vara bra. Nu kändes det som en oändlig förgrening av länkar som alltid ledde till något nytt och jag blev flera gånger hänvisad till gamla utdaterad instruktioner, t.ex. om .cgi.

**Comment by jeso20BTH** [comment]
Gick det bra att komma i gång med kursmomentet, fanns det svårigheter som du fastnade på?
Jag började någon vecka innan introveckan, och lyckades installera och komma igång med allting på egen hand. Det var dock lite rörigt och jag hade önskat att alla stegen hade varit tydligare. Länken till labbmiljön dyker till exempel inte upp förrän man är inne på Kmom01, kanske kan det vara värt att lägga instruktionerna till hur man installerar den längst upp på sidan? Det hade gett mig en tydligare överblick.  

Dbwebb-sidan i sig är rätt rörig. Det är svårt att navigera mellan de olika momenten, t.ex. mellan att fixa labbmiljön och kommandot dwebb. Jag tappade bort mig några gånger innan jag fick ordning på det.

Gäller kanske främst för de som väljer att påbörja innan kursstart, det är nog lättare att hänga med ifall man går på första genomgången.

**Comment by jeso20BTH** [comment]
Det som jag däremot fastnade var att instruktionerna till vissa uppgifter var krångligt formulerade. T.ex. 2.3 i lab1 var det många olika irriterande små steg, men det var väl meningen antar jag. Även 3.1 var jobbigt formulerad med de 10 soltimmarna, fast sen var den genomsnittliga solenergin över 24 timmar ändå uträknad, fast i slutändan var den inte det??? Plane-uppgiften var också svår. Alla era input-exempel var t.ex. heltal, så jag använde mig först av int istället för float för input och det stod inget mer i instruktionen, men jag fick därför en massa fel i dbwebb test. Var det med flit som ni undanhöll den informationen? Säkert för att lära oss problemlösning, men det var en av sakerna jag fick kämpa med. Sen fick jag såklart flera valideringsfel som jag var tvungen att googla och googla och googla för att fatta. Jag vet att jag sett något om vanliga valideringsfel någonstans på dbwebb-sidan, men det finns så otroligt många (visserligen bra) artiklar där att man ser inte skogen för alla träd.

**Comment by jeso20BTH** [comment]
KMOM02
Uppgiften om registreringsskyltarna var otydlig och här tycker jag att ni kan vara ännu tydligare exakt vad uppgiften är. Exempelvis ställer ni frågan om antalet registreringsskyltar vilket jag tycker borde bero på bokstävernas positioner också. Om man har 28 bokstäver att utgå ifrån och repetitioner tillåts borde ju antalet skyltar blir 28^3. Men enligt transportstyrelsen tillåts inte alla bokstäver i skyltarna vilket får mig att tro att ni inte vill att vi ska räkna med detta. För hur vet jag hur jag ska räkna då? Ska jag räkna 28!/(28-3)! * (antal kombinationer som jag få två siffor att bli den tredje) eller ska jag ta bort otillåtna bokstäver som dessutom är otillåtna på olika platser på skylten?
Jag har fortfarande inte förstått denna uppgift men lyckades att få rätt ändå. Tycker ni borde förtydliga denna. Annars tycker jag att de andra uppgifterna varit jättebra!

**Comment by Ewelina92** [comment]
Kmom01
"Jag uppskattar alla videor inspelningar som görs, men jag tycker det hade varit bra om vi hade fått även PDF på föreläsningar. Då hade varit lätt att gå tillbaka eller söka efter en särskild del i föreläsningen."

**Comment by jeso20BTH** [comment]
Kmom02
- Det skulle vara till stor hjälp om man fick ett lösningsförslag till alla uppgifter efter inlämning.

**Comment by jeso20BTH** [comment]
Kmom04
Förbättringsförslag... Kanske om man kan få test-fall man kan testa själv... eller göra en del av ett kursmoment till hur man ska testa sin kod på ett effektivt sätt?

När jag försöker ladda upp filerna på Canvas klagar Umbridge på att min kod inte skriver ut Error när man försöker byta pålats på saker med samma namn. Min kod hanterar visserligen inte detta, men står inte i beskrivningen att det ska ge error?

Men dbwebb test gav också fel för att swap-funktionen inte skulle tillåtas 
byta plats på två lika värden. Det kravet fanns inte med i uppgiften, då är 
det svårt att göra rätt. Så jag ger både ris och ros till Umbridge. För jag 
antar att det är Umbridge som används även när vi kör dbwebb test.

**Comment by AreonL** [comment]
- Vad tycker du om rättningssytemet Umbridge? Funkar det bra? Något vi kan förbättre?

Det funkar jättesnabbt och effektiv. Men ibland tycker jag att Umbridge script är inte flexibel. Eftersom man kan ha olika lösningar i koden och tror att de skulle funkar. Men ibland blir det inte så med Umbridge.

**Comment by jeso20BTH** [comment]
Kmom05
Marvin
Det verkar ha varit lite oklart skrivet att man i fråga 14 ska kalla båda funktionerna från main, det är många (inklusive jag) som har frågat om det i chatten. Så den kanske skulle kunna formuleras om lite. Men det är nog den enda kritiken jag har.

**Comment by AndreasArne** [comment]
har flyttat relevant information till den stora issue tråden.
